### ISSUE TITLE
Websockets not working?

### ISSUE THREAD

**Issue by nudabagana** [takoyaro/node-coinfield-api#1]
Hello, I'm trying to subsribe to ws order book feed. But I get nothing. I'm using this code:
```ts
const Coinfield = require('node-coinfield-api')({});
Coinfield.socket.subscribe.market('btceur');
Coinfield.socket.handler.on('orderbook_updates__btceur', (data: any) => {
	console.log(data);
});
```
I don't get any errors. I don't get any logs, it does nothing. Am I doing something wrong?

**Comment by takoyaro** [comment]
Hey @nudabagana ! This is a bit of an odd timing...Coinfield made undocumented changes to their API a few months back and I've been working on a new version of the wrapper that I happened to publish this morning.

Can you try updating to the latest version (`0.2.2`) and do this:

**Typescript**
```ts
import {Coinfield} from 'node-coinfield-api';
const cf = newCoinfield();
cf.socket.subscribe.market('xrpcad')
cf.socket.listener.on('orderbook_updates__xrpcad',(ob)=>{
   console.log(ob);
})
```

**Javascript**
```js
const Coinfield = require('node-coinfield-api').Coinfield;
const cf = new Coinfield();
cf.socket.subscribe.market('xrpcad')
cf.socket.listener.on('orderbook_updates__xrpcad',(ob)=>{
   console.log(ob);
})
```

**Comment by nudabagana** [comment]
I've tried the latest (0.2.3). Still getting nothing. Also when enabled DEBUG=*, I'm seeing this:
```
  socket.io-client:manager reconnect attempt error +0ms
  socket.io-client:manager will wait 2300ms before reconnect attempt +1ms
  socket.io-client:manager attempting reconnect +2s
  socket.io-client:manager readyState closed +1ms
  socket.io-client:manager opening https://ws.coinfield.com +0ms
  socket.io-client:manager connect attempt will timeout after 20000 +4ms
  socket.io-client:manager connect_error +1ms
  socket.io-client:manager cleanup +1ms
  socket.io-client:manager reconnect attempt error +0ms
  socket.io-client:manager will wait 5000ms before reconnect attempt +0ms
  ```
  Did you try to run this code and does it work for you?

**Comment by takoyaro** [comment]
I'm having no issues on both my local machines nor in REPL.
See REPL here: https://repl.it/@takoyaro/GroundedMajesticSquares#index.js

Response:
```js
 data: [
    { market: 'xrpcad', event: 'add', from: 'bids', data: [Array] },
    { market: 'xrpcad', event: 'add', from: 'bids', data: [Array] }
  ]
```
I feel like something is wrong on your end? Firewall issue? Browser Issue?

**Comment by nudabagana** [comment]
What Node.Js version are you using? Maybe it's related to it? I'm using v15.3.0. However I can see v12.6.1 in the REPL.

**Comment by nudabagana** [comment]
Indeed. Downgrading Node to v12.6.1 fixes the issue. It seems that Node v15 is breaking it.

**Comment by takoyaro** [comment]
I'm using V14.4. Just tested with Node v15 and the issue rising up is
```
Error: xhr poll error
    at XHR.Transport.onError (/Users/takoyaro/Documents/Projects/Non-Github/node-coinfield-api/node_modules/engine.io-client/lib/transport.js:68:13)
    at Request.<anonymous> (/Users/takoyaro/Documents/Projects/Non-Github/node-coinfield-api/node_modules/engine.io-client/lib/transports/polling-xhr.js:132:10)
    at Request.Emitter.emit (/Users/takoyaro/Documents/Projects/Non-Github/node-coinfield-api/node_modules/component-emitter/index.js:145:20)
    at Request.onError (/Users/takoyaro/Documents/Projects/Non-Github/node-coinfield-api/node_modules/engine.io-client/lib/transports/polling-xhr.js:314:8)
    at Timeout._onTimeout (/Users/takoyaro/Documents/Projects/Non-Github/node-coinfield-api/node_modules/engine.io-client/lib/transports/polling-xhr.js:274:12)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  type: 'TransportError',
  description: TypeError [ERR_INVALID_ARG_TYPE]: The "options.ciphers" property must be of type string. Received null
      at new NodeError (node:internal/errors:278:15)
      at validateString (node:internal/validators:123:11)
      at Object.createSecureContext (node:_tls_common:267:5)
      at Object.connect (node:_tls_wrap:1581:48)
      at Agent.createConnection (node:https:129:22)
      at Agent.createSocket (node:_http_agent:323:26)
      at Agent.addRequest (node:_http_agent:274:10)
      at new ClientRequest (node:_http_client:318:16)
      at request (node:https:313:10)
      at XMLHttpRequest.send (/Users/takoyaro/Documents/Projects/Non-Github/node-coinfield-api/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:495:17) {
    code: 'ERR_INVALID_ARG_TYPE'
```
Related to https://github.com/nodejs/node/issues/36292
Will keep an eye on this and keep the issue open until then.

In the meantime, use Node version <15
